name: Master Pipeline
run-name: Master Pipeline
on:
  workflow_call:
    inputs:
      deployment-namespace:
        type: string
        description: The namespace to which to deploy the project
        required: true
      minimum-code-coverage:
        type: number
        required: false
        description: The minimum percentage of code that must be covered to succeed. If unset, coverage isn't checked
      swagger-directory:
        type: string
        description: >
          The path to the directory within the calling repository that contains the OpenAPI files.
          Defaults to `docs/swagger`
        default: docs/swagger
        required: false
      internal-spec-file:
        type: string
        description: Name of the OpenAPI internal spec file. Defaults to `<repo-name>.yml`
        required: false
      public-spec-file:
        type: string
        description: Name of the OpenAPI public spec file. Defaults to `public.yml`
        default: public.yml
        required: false
      cluster:
        type: string
        description: |
          The cluster to deploy to. One of:
            - TST
            - ARO_ACC_CANADACENTRAL
            - ARO_PRD_CANADACENTRAL
            - ARO_PRD_CANADACENTRAL2
            - ARO_ACC_WESTEUROPE
            - ARO_PRD_WESTEUROPE
        required: false
        default: TST
jobs:
  unit-test:
    name: Lint, Unit Tests and Code Quality Checks (Sonarqube)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Reconfigure Git authentication
        uses: icemobilelab/github-actions-pipeline/actions/configure-github-authentication@v1
        with:
          github-pat: ${{ secrets.IM_CI_GITHUB_TOKEN }}
      - name: Unit tests
        uses: icemobilelab/github-actions-pipeline/actions/unit-lint-sonar-checks@v1
        with:
          minimum-code-coverage: ${{ inputs.minimum-code-coverage }}
  build:
    name: Build and Deploy image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install and configure oc
        uses: icemobilelab/github-actions-pipeline/actions/install-and-configure-oc@v1
        with:
          openshift-server-api-url: ${{ secrets.ARO_TST_API_URL }}
          openshift-auth-token: ${{ secrets.ARO_TST_AUTH_TOKEN }}
      - name: Build Image
        uses: icemobilelab/github-actions-pipeline/actions/build-image@v1
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and configure oc
        uses: icemobilelab/github-actions-pipeline/actions/install-and-configure-oc@v1
        with:
          openshift-server-api-url: ${{ secrets.ARO_TST_API_URL }}
          openshift-auth-token: ${{ secrets.ARO_TST_AUTH_TOKEN }}
      - name: Reconfigure Git authentication
        uses: icemobilelab/github-actions-pipeline/actions/configure-github-authentication@v1
        with:
          github-pat: ${{ secrets.IM_CI_GITHUB_TOKEN }}
      - name: Create Integration Test Namespace
        id: create-ns
        uses: icemobilelab/github-actions-pipeline/actions/create-testing-namespace@v1
      - name: Install and configure Ansible Vault
        id: ansible-vault
        uses: icemobilelab/github-actions-pipeline/actions/configure-ansible-vault@v1
        with:
          ansible-vault-key: ${{ secrets.ANSIBLE_VAULT_KEY }}
      - name: Deploy dependencies
        uses: icemobilelab/github-actions-pipeline/actions/deploy-dependencies@v1
        with:
          namespace: ${{ steps.create-ns.outputs.testing-namespace }}
          ansible-vault-password-file: ${{ steps.ansible-vault.outputs.ansible-vault-password-file }}
      - name: Deploy project
        uses: icemobilelab/github-actions-pipeline/actions/deploy-project@v1
        with:
          namespace: ${{ steps.create-ns.outputs.testing-namespace }}
          ansible-vault-password-file: ${{ steps.ansible-vault.outputs.ansible-vault-password-file }}
      - name: Integration Tests
        uses: icemobilelab/github-actions-pipeline/actions/run-integration-tests@v1
        with:
          namespace: ${{ steps.create-ns.outputs.testing-namespace }}
      - name: Archive integration test logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: integration-tests-logs
          path: |
            integration-tests-logs.txt
  deploy-project:
    name: Deploy to TST
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - integration-tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and configure oc
        uses: icemobilelab/github-actions-pipeline/actions/install-and-configure-oc@v1
        with:
          openshift-server-api-url: ${{ secrets.ARO_TST_API_URL }}
          openshift-auth-token: ${{ secrets.ARO_TST_AUTH_TOKEN }}
      - name: Install and configure Ansible Vault
        id: ansible-vault
        uses: icemobilelab/github-actions-pipeline/actions/configure-ansible-vault@v1
        with:
          ansible-vault-key: ${{ secrets.ANSIBLE_VAULT_KEY }}
      - name: Deploy project
        uses: icemobilelab/github-actions-pipeline/actions/deploy-project@v1
        with:
          namespace: ${{ inputs.deployment-namespace }}
          ansible-vault-password-file: ${{ steps.ansible-vault.outputs.ansible-vault-password-file }}
      - name: Deploy to 3scale
        uses: icemobilelab/github-actions-pipeline/actions/deploy-to-3scale@v1
        with:
          swagger-directory: ${{ inputs.swagger-directory }}
          internal-spec-file: ${{ inputs.internal-spec-file }}
          public-spec-file: ${{ inputs.public-spec-file }}
          cluster: ${{ inputs.cluster }}

  cleanup:
    if: ${{ always() }}
    name: Log collection and cleanup
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - integration-tests
    steps:
      - name: Install and configure oc
        uses: icemobilelab/github-actions-pipeline/actions/install-and-configure-oc@v1
        with:
          openshift-server-api-url: ${{ secrets.ARO_TST_API_URL }}
          openshift-auth-token: ${{ secrets.ARO_TST_AUTH_TOKEN }}
      - name: Get testing namespace
        id: testing-ns
        uses: icemobilelab/github-actions-pipeline/actions/get-testing-namespace@v1
      - name: Collect pod logs
        id: collect-logs
        uses: icemobilelab/github-actions-pipeline/actions/collect-pod-logs@v1
        with:
          namespace: ${{ steps.testing-ns.outputs.testing-namespace }}
      - name: Archive logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: pod-logs
          path: |
            ${{ steps.collect-logs.outputs.output-directory }}/*.txt
      - name: Cleanup
        if: ${{ always() }}
        uses: icemobilelab/github-actions-pipeline/actions/cleanup-integration-test-namespace@v1
        with:
          namespace: ${{ steps.testing-ns.outputs.testing-namespace }}
